In [1]:
#import libraries
import numpy as np
import torch

In [5]:
#create a vector

new_vector = np.array([[1,2,3,4,5]])
print('new_vector \n',new_vector), print(' ')

#transposing a vector
print('new_vector transposed \n',new_vector.T), print(' ')

#transposing the transpose!
newV = new_vector.T.T
print('transpose of the transpose \n',newV)

new_vector 
 [[1 2 3 4 5]]
 
new_vector transposed 
 [[1]
 [2]
 [3]
 [4]
 [5]]
 
transpose of the transpose 
 [[1 2 3 4 5]]


Using Pytorch.

In [6]:
#First create a vector
torch_vector = torch.tensor([[1,2,3,4]])
print("torch vector \n", torch_vector), print(' ')

#Transpose the created vector.
tvT = torch_vector.T
print("torch transposed \n", tvT)

#Transposing the transpose
print("Original \n", tvT.T), print(' ')

torch vector 
 tensor([[1, 2, 3, 4]])
 
torch transposed 
 tensor([[1],
        [2],
        [3],
        [4]])
Original 
 tensor([[1, 2, 3, 4]])
 


(None, None)

In [19]:

#Examining the Data Types.
#checked the side bar on colab.

print(f'newV is of type: {type(newV)}')
print(f'new_vector is of type: {type(new_vector)}')
print(f'torch_vector is of type: {type(torch_vector)}')
print(f'tvT is of type: {type(tvT)}')


newV is of type: <class 'numpy.ndarray'>
new_vector is of type: <class 'numpy.ndarray'>
torch_vector is of type: <class 'torch.Tensor'>
tvT is of type: <class 'torch.Tensor'>


Code Snippet $ deep learning class.
##### Author: Lawrence
##### Tutor: Mike X Cohen